Refactor git-multi script for improved readability

diff --git a/bin/git-multi b/bin/git-multi
--- a/bin/git-multi
+++ b/bin/git-multi
@@ -6,20 +6,20 @@ shopt -s globstar nullglob
 failures=()
 
 while read -r -d '' repo; do
-  if [[ -z "$repo" ]]; then
-    continue
-  fi
-  repo="${repo%/.git/}"
-  echo -e "\e[96m\e[1m==> \e[39m$repo\e[0m"
-  if ! git -C "$repo" "$@"; then
-    failures+=("$repo")
-  fi
+    if [[ -z "$repo" ]]; then
+        continue
+    fi
+    repo="${repo%/.git/}"
+    echo -e "\e[96m\e[1m==> \e[39m$repo\e[0m"
+    if ! git -C "$repo" "$@"; then
+        failures+=("$repo")
+    fi
 done < <(printf '%s\0' **/.git/ | sort -fz)
 
 if [[ ${#failures[@]} -gt 0 ]]; then
-  echo
+    echo
 fi
 
 for failure in "${failures[@]}"; do
-  echo -e "\e[31m\e[1m==> \e[39m$failure\e[0m"
+    echo -e "\e[31m\e[1m==> \e[39m$failure\e[0m"
 done
